{{ $bdir := regexSplit ( list .chezmoi.homeDir "/" | join "" ) .bindir -1 | last }}

[".config/bat/themes/Catppuccin-mocha.tmTheme"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/bat/main/Catppuccin-mocha.tmTheme"
  refreshPeriod = "24h"

[".config/btop/themes/catppuccin_mocha.theme"]
 type = "file"
 url = "https://raw.githubusercontent.com/catppuccin/btop/main/catppuccin_mocha.theme"
 refreshPeriod = "24h"

["{{- $bdir -}}/starship"]
  type = "file"
  url = "https://github.com/starship/starship/releases/download/{{ (gitHubLatestRelease "starship/starship").TagName }}/starship-x86_64-unknown-linux-musl.tar.gz"
  executable = true
  ["{{- $bdir -}}/starship" .filter]
    command = "tar"
    args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "starship"]

["{{- $bdir -}}/fzf"]
  type = "file"
  url = "https://github.com/junegunn/fzf/releases/download/{{ (gitHubLatestRelease "junegunn/fzf").TagName }}/fzf-{{ (gitHubLatestRelease "junegunn/fzf").TagName }}-linux_amd64.tar.gz"
  executable = true
  ["{{- $bdir -}}/fzf" .filter]
    command = "tar"
    args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "fzf"]

["{{- $bdir -}}/rg"]
  type = "file"
  url = "https://github.com/BurntSushi/ripgrep/releases/download/{{ (gitHubLatestRelease "BurntSushi/ripgrep").TagName }}/ripgrep-{{ (gitHubLatestRelease "BurntSushi/ripgrep").TagName }}-x86_64-unknown-linux-musl.tar.gz"
  ["{{- $bdir -}}/rg" .filter]
    command = "tar"
    args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "ripgrep-{{ (gitHubLatestRelease "BurntSushi/ripgrep").TagName }}-x86_64-unknown-linux-musl/complete/rg.bash"]

["{{- $bdir -}}/jq"]
  type = "file"
  url = "https://github.com/stedolan/jq/releases/download/{{ (gitHubLatestRelease "stedolan/jq").TagName }}/jq-linux64"
  executable = true
